export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const CREATE_SUPERVISOR_SUCSESS = "CREATE_SUPERVISOR_SUCSESS";
export const CREATE_SUPERVISOR_FAIL = "CREATE_SUPERVISOR_FAIL";