export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const FORGOT_EMAIL_CHECK_SUCCESS = "FORGOT_EMAIL_CHECK_SUCCESS";
export const FORGOT_EMAIL_CHECK_FAIL = "FORGOT_EMAIL_CHECK_FAIL";

export const CODE_VALIDATE_SUCCESS = "CODE_VALIDATE_SUCCESS";
export const CODE_VALIDATE_FAIL = "CODE_VALIDATE_FAIL";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const CREATE_NEW_JOB_SUCCESS = "CREATE_NEW_JOB_SUCCESS";
export const CREATE_NEW_JOB_FAIL = "CREATE_NEW_JOB_FAIL";

export const CREATE_SUPERVISOR_SUCSESS = "CREATE_SUPERVISOR_SUCSESS";
export const CREATE_SUPERVISOR_FAIL = "CREATE_SUPERVISOR_FAIL";

export const CREATE_DECORATOR_SUCSESS = "CREATE_DECORATOR_SUCSESS";
export const CREATE_DECORATOR_FAIL = "CREATE_DECORATOR_FAIL";

export const SEARCH_SUPERVISOR_SUCCESS = "SEARCH_SUPERVISOR_SUCCESS";
export const SEARCH_SUPERVISOR_FAIL = "SEARCH_SUPERVISOR_FAIL";

export const SEARCH_DECORATOR_SUCCESS = "SEARCH_DECORATOR_SUCCESS";
export const SEARCH_DECORATOR_FAIL = "SEARCH_DECORATOR_FAIL";

export const UPDATE_SUPERVISOR_SUCCESS = "UPDATE_SUPERVISOR_SUCCESS";
export const UPDATE_SUPERVISOR_FAIL = "UPDATE_SUPERVISOR_FAIL";

export const UPDATE_DECORATOR_SUCCESS = "UPDATE_DECORATOR_SUCCESS";
export const UPDATE_DECORATOR_FAIL = "UPDATE_DECORATOR_FAIL";

export const CREATE_HAND_OVER_SHEET_SUCCESS = "CREATE_HAND_OVER_SHEET_SUCCESS";
export const CREATE_HAND_OVER_SHEET_FAIL = "CREATE_HAND_OVER_SHEET_FAIL";

export const CREATE_MAKE_READY_SHEET_SUCCESS = "CREATE_MAKE_READY_SHEET_SUCCESS";
export const CREATE_MAKE_READY_SHEET_FAIL = "CREATE_MAKE_READY_SHEET_FAIL";

export const CREATE_REMEDIAL_WORK_SHEET_SUCCESS = "CREATE_REMEDIAL_WORK_SHEET_SUCCESS";
export const CREATE_REMEDIAL_WORK_SHEET_FAIL = "CREATE_REMEDIAL_WORK_SHEET_FAIL";

export const CREATE_SCOPE_FORM_SUCCESS = "CREATE_SCOPE_FORM_SUCCESS";
export const CREATE_SCOPE_FORM_FAIL = "CREATE_SCOPE_FORM_FAIL";

export const CREATE_PRE_WRRANTY_FORM_SUCCESS = "CREATE_PRE_WRRANTY_FORM_SUCCESS";
export const CREATE_PRE_WRRANTY_FORM_FAIL = "CREATE_PRE_WRRANTY_FORM_FAIL";

export const CREATE_QUALITY_ANSURANCE_FORM_SUCCESS = "CREATE_QUALITY_ANSURANCE_FORM_SUCCESS";
export const CREATE_QUALITY_ANSURANCE_FORM_FAIL = "CREATE_QUALITY_ANSURANCE_FORM_FAIL";

export const INSERT_ACCURATE_DAY_WOEK_SHEET_CREATE = "INSERT_ACCURATE_DAY_WOEK_SHEET_CREATE";
export const INSERT_ACCURATE_DAY_WOEK_SHEET_FAIL = "INSERT_ACCURATE_DAY_WOEK_SHEET_FAIL";

export const INSERT_DECORATION_RECORD_SUCCESS = "INSERT_DECORATION_RECORD_SUCCESS";
export const INSERT_DECORATION_RECORD_FAIL = "INSERT_DECORATION_RECORD_FAIL";

export const INSERT_MISCOAT_SUCCESS = "INSERT_MISCOAT_SUCCESS";
export const INSERT_MISCOAT_FAIL = "INSERT_MISCOAT_FAIL";

export const INSERT_SITE_INSTRUCTION_SUCCESS = "INSERT_SITE_INSTRUCTION_SUCCESS";
export const INSERT_SITE_INSTRUCTION_FAIL = "INSERT_SITE_INSTRUCTION_FAIL";

export const INSERT_VERIFICATION_WORK_SUCCESS = "INSERT_VERIFICATION_WORK_SUCCESS";
export const INSERT_VERIFICATION_WORK_FAIL = "INSERT_VERIFICATION_WORK_FAIL";

export const INSERT_CLEAN_UP_FORM_SUCCESS = "INSERT_CLEAN_UP_FORM_SUCCESS";
export const INSERT_CLEAN_UP_FORM_FAIL = "INSERT_CLEAN_UP_FORM_FAIL";

export const INSERT_ELECTRICAL_EQUIPMENT_FORM_SUCCESS = "INSERT_ELECTRICAL_EQUIPMENT_FORM_SUCCESS";
export const INSERT_ELECTRICAL_EQUIPMENT_FORM_FAIL = "INSERT_ELECTRICAL_EQUIPMENT_FORM_FAIL";

export const INSERT_HARMFUL_SUBSTANCE_FORM_SUCCESS = "INSERT_HARMFUL_SUBSTANCE_FORM_SUCCESS";
export const INSERT_HARMFUL_SUBSTANCE_FORM_FAIL = "INSERT_HARMFUL_SUBSTANCE_FORM_FAIL";

export const INSERT_HOUSE_KEEPING_FORM_SUCCESS = "INSERT_HOUSE_KEEPING_FORM_SUCCESS";
export const INSERT_HOUSE_KEEPING_FORM_FAIL = "INSERT_HOUSE_KEEPING_FORM_FAIL";

export const INSERT_LADDER_CHECKLIST_FORM_SUCCESS = "INSERT_LADDER_CHECKLIST_FORM_SUCCESS";
export const INSERT_LADDER_CHECKLIST_FORM_FAIL = "INSERT_LADDER_CHECKLIST_FORM_FAIL";

export const INSERT_METHOD_STATEMENT_FORM_SUCCESS = "INSERT_METHOD_STATEMENT_FORM_SUCCESS";
export const INSERT_METHOD_STATEMENT_FORM_FAIL = "INSERT_METHOD_STATEMENT_FORM_FAIL";

export const INSERT_PERSONAL_PROTECTIVE_FORM_SUCCESS = "INSERT_PERSONAL_PROTECTIVE_FORM_SUCCESS";
export const INSERT_PERSONAL_PROTECTIVE_FORM_FAIL = "INSERT_PERSONAL_PROTECTIVE_FORM_FAIL";

export const INSERT_ON_SITE_DECORATION_FORM_SUCCESS = "INSERT_ON_SITE_DECORATION_FORM_SUCCESS";
export const INSERT_ON_SITE_DECORATION_FORM_FAIL = "INSERT_ON_SITE_DECORATION_FORM_FAIL";

export const INSERT_RECORD_OF_PROJECT_FORM_SUCCESS = "INSERT_RECORD_OF_PROJECT_FORM_SUCCESS";
export const INSERT_RECORD_OF_PROJECT_FORM_FAIL = "INSERT_RECORD_OF_PROJECT_FORM_FAIL";


export const UPDATE_PLOT_REPORT = "UPDATE_PLOT_REPORT";
export const UPDATE_HEALTH_REPORT = "UPDATE_HEALTH_REPORT";
export const UPDATE_VERIFICATION_REPORT = "UPDATE_VERIFICATION_REPORT";



export const RESET_LOGIN_FLAG='RESET_LOGIN_FLAG'


export const INSERT_TBT_COSH_FORM_SUCCESS = "INSERT_TBT_COSH_FORM_SUCCESS";
export const INSERT_TBT_COSH_FORM_FAIL = "INSERT_TBT_COSH_FORM_FAIL";

export const INSERT_TBT_FIRE_FORM_SUCCESS = "INSERT_TBT_FIRE_FORM_SUCCESS";
export const INSERT_TBT_FIRE_FORM_FAIL = "INSERT_TBT_FIRE_FORM_FAIL";

export const INSERT_TBT_SLIP_FORM_SUCCESS = "INSERT_TBT_SLIP_FORM_SUCCESS";
export const INSERT_TBT_SLIP_FORM_FAIL = "INSERT_TBT_SLIP_FORM_FAIL";

export const INSERT_TBT_COVID_FORM_SUCCESS = "INSERT_TBT_COVID_FORM_SUCCESS";
export const INSERT_TBT_COVID_FORM_FAIL = "INSERT_TBT_COVID_FORM_FAIL";

export const INSERT_TBT_HOUSEKEEPING_FORM_SUCCESS = "INSERT_TBT_HOUSEKEEPING_FORM_SUCCESS";
export const INSERT_TBT_HOUSEKEEPING_FORM_FAIL = "INSERT_TBT_HOUSEKEEPING_FORM_FAIL";

export const INSERT_TBT_MOBILE_FORM_SUCCESS = "INSERT_TBT_MOBILE_FORM_SUCCESS";
export const INSERT_TBT_MOBILE_FORM_FAIL = "INSERT_TBT_MOBILE_FORM_FAIL";

export const INSERT_TBT_RESPIRATORY_FORM_SUCCESS = "INSERT_TBT_RESPIRATORY_FORM_SUCCESS";
export const INSERT_TBT_RESPIRATORY_FORM_FAIL = "INSERT_TBT_RESPIRATORY_FORM_FAIL";

export const INSERT_TBT_SILICA_FORM_SUCCESS = "INSERT_TBT_SILICA_FORM_SUCCESS";
export const INSERT_TBT_SILICA_FORM_FAIL = "INSERT_TBT_SILICA_FORM_FAIL";

export const INSERT_TBT_DRUGS_FORM_SUCCESS = "INSERT_TBT_DRUGS_FORM_SUCCESS";
export const INSERT_TBT_DRUGS_FORM_FAIL = "INSERT_TBT_DRUGS_FORM_FAIL";

export const INSERT_TBT_VOLIENCE_FORM_SUCCESS = "INSERT_TBT_VOLIENCE_FORM_SUCCESS";
export const INSERT_TBT_VOLIENCE_FORM_FAIL = "INSERT_TBT_VOLIENCE_FORM_FAIL";

export const INSERT_TBT_WORKING_FORM_SUCCESS = "INSERT_TBT_WORKING_FORM_SUCCESS";
export const INSERT_TBT_WORKING_FORM_FAIL = "INSERT_TBT_WORKING_FORM_FAIL";

export const INSERT_TBT_TOOLBOX_FORM_SUCCESS = "INSERT_TBT_TOOLBOX_FORM_SUCCESS";
export const INSERT_TBT_TOOLBOX_FORM_FAIL = "INSERT_TBT_TOOLBOX_FORM_FAIL";

export const INSERT_TBT_INVENTORY_FORM_SUCCESS = "INSERT_TBT_INVENTORY_FORM_SUCCESS";
export const INSERT_TBT_INVENTORY_FORM_FAIL = "INSERT_TBT_INVENTORY_FORM_FAIL";

export const INSERT_TBT_DAILYBREIFING_FORM_SUCCESS = "INSERT_TBT_DAILYBREIFING_FORM_SUCCESS";
export const INSERT_TBT_DAILYBREIFING_FORM_FAIL = "INSERT_TBT_DAILYBREIFING_FORM_FAIL";

export const INSERT_TBT_HEALTHSAFETY_FORM_SUCCESS = "INSERT_TBT_HEALTHSAFETY_FORM_SUCCESS";
export const INSERT_TBT_HEALTHSAFETY_FORM_FAIL = "INSERT_TBT_HEALTHSAFETY_FORM_FAIL";