export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const CREATE_SUPERVISOR_SUCSESS = "CREATE_SUPERVISOR_SUCSESS";
export const CREATE_SUPERVISOR_FAIL = "CREATE_SUPERVISOR_FAIL";

export const CREATE_NEW_JOB_SUCCESS = "CREATE_NEW_JOB_SUCCESS";
export const CREATE_NEW_JOB_FAIL = "CREATE_NEW_JOB_FAIL";

export const CREATE_DECORATOR_SUCSESS = "CREATE_DECORATOR_SUCSESS";
export const CREATE_DECORATOR_FAIL = "CREATE_DECORATOR_FAIL";

export const SEARCH_SUPERVISOR_SUCCESS = "SEARCH_SUPERVISOR_SUCCESS";
export const SEARCH_SUPERVISOR_FAIL = "SEARCH_SUPERVISOR_FAIL";